http:
  routers:
    api:
      rule: 'Host(`api.quvel.127.0.0.1.nip.io`) || Host(`api.quvel.192.168.86.20.nip.io`)' # REPLACE_WITH_LOCAL_IP
      entryPoints: websecure
      service: api
      tls: {}

  services:
    api:
      loadBalancer:
        servers:
          - url: 'http://quvel-app:8000'
