http:
  routers:
    api-local:
      rule: 'Host(`api.quvel.127.0.0.1.nip.io`) || Host(`api.quvel-two.127.0.0.1.nip.io`)'
      entryPoints: websecure
      service: api-local
      tls: {}

    api-lan:
      rule: 'Host(`api.quvel.192.168.86.21.nip.io`) || Host(`api.quvel-two.192.168.86.21.nip.io`)' # REPLACE_WITH_LOCAL_IP
      entryPoints: websecure
      service: api-lan
      tls: {}

  services:
    api-local:
      loadBalancer:
        servers:
          #          - url: 'http://127.0.0.1:8000' # If not using docker
          - url: 'http://host.docker.internal:8000' # If serving app from local machine
    #          - url: 'http://quvel-app:8000' # If serving from Docker

    api-lan:
      loadBalancer:
        servers:
          #          - url: 'http://127.0.0.1:8000' # If not using docker
          - url: 'http://host.docker.internal:8000' # If serving from local machine
#          - url: 'http://api-lan:8000' # If serving from Docker
