# HMR needs to support SSL all the way through from browser -> traefik -> vite dev server
http:
  routers:
    web:
      rule: 'Host(`quvel.127.0.0.1.nip.io`) || Host(`quvel.192.168.86.228.nip.io`)' # REPLACE_WITH_LOCAL_IP
      entryPoints: websecure
      service: web
      tls: {}

    web-ws:
      rule: '(Host(`quvel.127.0.0.1.nip.io`) || Host(`quvel.192.168.86.228.nip.io`)) && PathPrefix(`/hmr`)' # REPLACE_WITH_LOCAL_IP
      entryPoints: websecure
      service: web-ws
      tls: {}
      middlewares:
        - websocket-headers

    capacitor:
      rule: 'Host(`cap-tenant.quvel.127.0.0.1.nip.io`) || Host(`cap-tenant.quvel.192.168.86.228.nip.io`)' # REPLACE_WITH_LOCAL_IP
      entryPoints: websecure
      service: capacitor
      tls: {}

  services:
    web:
      loadBalancer:
        servers:
#          - url: 'https://quvel-frontend:9000'
          - url: 'https://host.docker.internal:3000' # If serving from local machine
        serversTransport: 'insecureTransport' # Supports self-signed certificates

    web-ws:
      loadBalancer:
        servers:
          - url: 'https://quvel-frontend:9001'
        serversTransport: 'insecureTransport' # Supports self-signed certificates

    capacitor:
      loadBalancer:
        servers:
          - url: 'https://host.docker.internal:3002'
        serversTransport: 'insecureTransport' # Supports self-signed certificates

  middlewares:
    websocket-headers:
      headers:
        customRequestHeaders:
          Connection: 'Upgrade'
          Upgrade: 'websocket'
        customResponseHeaders:
          Sec-WebSocket-Accept: '{Sec-WebSocket-Key}'

  serversTransports:
    insecureTransport:
      insecureSkipVerify: true
