http:
  routers:
    web:
      rule: 'Host(`quvel.127.0.0.1.nip.io`)'
      entryPoints: websecure
      service: web
      tls: {}

    web-ws:
      rule: 'Host(`quvel.127.0.0.1.nip.io`) && PathPrefix(`/hmr`)'
      entryPoints: websecure
      service: web-ws
      tls: {}
      middlewares:
        - websocket-headers

  services:
    web:
      loadBalancer:
        servers:
          - url: 'https://quvel-frontend:9000'
        serversTransport: 'insecureTransport'

    web-ws:
      loadBalancer:
        servers:
          - url: 'https://quvel-frontend:9001'
        serversTransport: 'insecureTransport'

  middlewares:
    websocket-headers:
      headers:
        customRequestHeaders:
          Connection: 'Upgrade'
          Upgrade: 'websocket'
        customResponseHeaders:
          Sec-WebSocket-Accept: '{Sec-WebSocket-Key}'

  serversTransports:
    insecureTransport:
      insecureSkipVerify: true
